### ISSUE TITLE
mate-hud is causing a complete input deadlock

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/mate-hud#16]
@vkareh After some more thorough testing `mate-hud` 18.04.0 is causing a complete input lock up for keyboard and mouse. 

This can be reproduced using `mate-hud` from git master on Ubuntu MATE 18.04 with a layout activated that uses the Global Menu, such as Mutiny, Cupertino or Contemporary. I was able to create the deadlock by invoking things that required `Alt`, such as `Alt + PrtScn` or `Ctrl + Alt +t`. It doesn't happen 100% of the time but after a few uses of `Alt` the lock up happens. The only recourse is to switch to a vt and kill `mate-hud` then switch back to the desktop vt.

The  best way to test this is using the [Ubuntu MATE 18.04 daily live image](http://cdimage.ubuntu.com/ubuntu-mate/daily-live/current/) on actual hardware and replacing `mate-hud` with the version in git master.

Reverting this patch resolves the issue:

  * https://github.com/ubuntu-mate/mate-hud/commit/92d4fe2c17893ef8410347b378fad079751adb7e

So I will publish a new `.deb` that reverts that commit via patch for the time being :smile:

**Comment by vkareh** [comment]
@flexiondotorg - I made some fixes to the code, but I still the get input deadlock ocassionally. However, it only happens when mate-hud is started along with the desktop environment. If I run mate-hud after the computer is fully booted, I don't get the input lock. I have vague memories of this being an issue for earlier iterations of mate-hud during the 17.10 dev cycle and I think I remember you changing where/when in the boot process it gets loaded. Could it be related?

**Comment by flexiondotorg** [comment]
@vkareh I've been making some unrelated changes to `mate-hud` this morning and managed to encounter a deadlock, the was output to stdout just before the lock up happened:

```
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 518, sequence_number = 22, major_opcode = 28, minor_opcode = 0
```

**Comment by flexiondotorg** [comment]
@vkareh I may have found a solution. I will test over the coming days to confirm. Looks like it may not be a `mate-hud` issue.

**Comment by flexiondotorg** [comment]
Sadly I was wrong, the lockups still happen.

**Comment by flexiondotorg** [comment]
@vkareh I'm using the new release with the potential lock-up fix, sadly I just experienced a lock up. I run Compiz so I am now testing to Marco to see if that is a factor.

**Comment by flexiondotorg** [comment]
Locked up with Marco too.

**Comment by vkareh** [comment]
Yeah, same experience here. However, if I start it directly from the command line after the desktop is fully up, I don't get the locks... :/

**Comment by flexiondotorg** [comment]
I'm still experiencing lock ups with https://github.com/ubuntu-mate/mate-hud/commit/d4d57e4263693df2029cb89d10303fb781934442 applied. I'll test with the Whitelist Caja navigation shortcuts change applied.

**Comment by vkareh** [comment]
Okay, back to the drawing board :/

**Comment by flexiondotorg** [comment]
Two hours of `mate-hud` being active with https://github.com/ubuntu-mate/mate-hud/pull/21 applied. No lock ups so far...

**Comment by flexiondotorg** [comment]
Just had a lock up.

**Comment by vkareh** [comment]
I'm testing extra checks, like wrapping the entire keybinding processing block in try/catch and call allow_events if it ever fails - I'll test more on my side to see what happens...

Did #21 solve the caja navigation for you?

**Comment by flexiondotorg** [comment]
Yes, #21 solved Caja navigation as best as I can tell. I've never used those keybindings in Caja before.

**Comment by vkareh** [comment]
I haven't gotten an input lock up since the try-catch update. Have you? We should maybe keep this issue open for a little while longer, but I'm really looking forward to when we can close it!! :) :)

**Comment by flexiondotorg** [comment]
I have not.

**Comment by vkareh** [comment]
I think we should leave it off by default. It decreases the chances of any remaining issues for users that don't want/need/expect the HUD. Mutiny should have it on, of course, as that's part of the overall experience, but other than that I think users that really want it will know to enable it.

**Comment by flexiondotorg** [comment]
I've not experienced a lock up for nearly two weeks on multiple computers.

**Comment by jonpolak** [comment]
Happening again on 23.04 (Ubuntu Mate). Same issues, using Alt a few times in combination with other keys. Killing  `rofi` (the display agent called by `mate-hub`) solved the issue.
