### ISSUE TITLE
HUD Shortcut messes with chrome and terminal shortcuts

### ISSUE THREAD

**Issue by otavioschwanck** [ubuntu-mate/mate-hud#24]
For tab change, i use alt + numbers.  When i use mate-hud, i have to hold for a while alt button, then, press the number.  If i instantily press alt + number, the tab not change

**Comment by vkareh** [comment]
@otavioschwanck - what version of Ubuntu MATE are you using?

**Comment by otavioschwanck** [comment]
Ubuntu MATE 17.10, Mate 1.18.0

**Comment by flexiondotorg** [comment]
This issue is fixed in Ubuntu MATE 18.04 daily.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/ubuntu-mate/mate-hud/commit/92d4fe2c17893ef8410347b378fad079751adb7e
