### ISSUE TITLE
[ Feature Request ] Also display Keyboard Shortcuts

### ISSUE THREAD

**Issue by ezriharmusial** [ubuntu-mate/mate-hud#26]
Thanks Guys! Really enjoy the HUD! Made work so much more faster and efficient. 

Was wondering if it is also possible to Display the Assigned Keyboard Shortcut. as displayed in the normal menu.

Sorry not a Python Programmer (yet).

Peace!

**Comment by CreamyCookie** [comment]
Would also love to see this! 

And I agree, great work on the HUD, Ubuntu Mate developers! :+1:
