### ISSUE TITLE
Feature: Populate HUD with dbus commands for GTK3 apps

### ISSUE THREAD

**Issue by ghost** [ubuntu-mate/mate-hud#32]
GTK3 apps are increasingly common and they've dispensed with the traditional menus. This means that the HUD relying on appmenu modules will become increasingly obsolete.

 However, you can still search the application functionality is still exposed via dbus and one developer has already made a HUD for these apps called [Plotnus](https://github.com/p-e-w/plotinus). It would be nice if this was integrated into Mate-Hud.

**Comment by CreamyCookie** [comment]
That would be awesome.

**Comment by flexiondotorg** [comment]
Added via https://github.com/ubuntu-mate/mate-hud/commit/d6cd57e474a8daca20ebfc70a2b9e8a44e78f22d
