### ISSUE TITLE
Feature: opt-in predictive results like unity and/or "pinned" commands?

### ISSUE THREAD

**Issue by developer91234** [ubuntu-mate/mate-hud#39]
I think the HUD interface is eventually going to need some kind of way to store preferences per application, both to get around bugs and to add new functionality (like custom commands).

One idea would be to allow the user to store previous selections for predictive HUD search, or to allow the pinning of certain commands. This makes a great difference in productivity because it allows you to type just one or two letters and hit enter to do to where you need.

**Comment by vkareh** [comment]
An easy way of doing this without user interaction would be to move to the top the last selected options. That way whatever they are most likely to use will often come up above less used options
