### ISSUE TITLE
Dulplicate menu bar

### ISSUE THREAD

**Issue by tommyvct** [ubuntu-mate/mate-hud#41]
Instead of this:
![Screenshot at 2019-05-20 22-38-44](https://user-images.githubusercontent.com/7903172/58030157-a5286980-7b50-11e9-95e1-c9da3eee2a6a.png)
I want something like this:
![Screenshot at 2019-05-20 22-46-21](https://user-images.githubusercontent.com/7903172/58030425-1cf69400-7b51-11e9-8cbf-9b421bdd37cd.png)

Or how to disable in application menubar for all programs?

**Comment by flexiondotorg** [comment]
Sorry, GitHub issues are for reporting bugs not requesting support. Please ask the question on the Ubuntu MATE Forum - https://ubuntu-mate.community

**Comment by tommyvct** [comment]
This IS a bug. 
I tried it on both Ubuntu MATE 19.04 and Manjaro, there are always duplicate menu bars. I also tried poking around dconf settings on both distro, but nothing works.
On Ubuntu MATE, the problem is actually better than Manjaro. Open Caja and press ALT, the HUD search function will be invoked. But after the search function is dismissed, there will be dulplicate menu bar until logout.

**Comment by tommyvct** [comment]
the HUD will never work for program running under root.
try launch `pkexec caja` or `pkexec synaptics`
