### ISSUE TITLE
Global menus switch to local menus when hud is used

### ISSUE THREAD

**Issue by NeoTheThird** [ubuntu-mate/mate-hud#42]
With a fresh and updated install of Ubuntu MATE 19.04 and the contemporary preset, using the hud turns the global menu into a local menu and moves it into the respective window.

Please let me know if you need any version/config information or logs.

**Comment by vkareh** [comment]
I can confirm this.

The `mate-hud` checks whether `appmenu-mate` is running before deciding to kill the `appmenu-registrar`, but I cannot see such a process in my system. Did something change in `vala-panel-appmenu`?

To fix this, I think we should verify whether the registrar process was running prior to the hud starting it, then killing it only if it wasn't. Regardless of the existence of `appmenu-mate`.

Other thoughts:
I wonder if we want to synchronize the monitor setting with the global menu configuration. Rofi supports the following modes:
```
$ man rofi
...
-monitor name
 Select monitor to display rofi on. It accepts as input: primary (if primary output is set), the xrandr output name, or integer number (in order of detection). Negative numbers  are  handled  differently:
•   -1: the currently focused monitor.
•   -2: the currently focused window (that is, rofi will be displayed on top of the focused window).
•   -3: Position at mouse (overrides the location setting to get normal context menu behavior.)
•   -4: the monitor with the focused window.
•   -5: the monitor that shows the mouse pointer.
```
We currently use `-monitor 2`, but we could change it to `primary` or `-4` when global menus are enabled.

Thoughts?

**Comment by vkareh** [comment]
Update, turns out vala-panel-appmenu moved to in-process, making it harder to determine if the process is running: https://gitlab.com/vala-panel-project/vala-panel-appmenu/commit/c5d20e73d47ea4805697553401fcb7633fc402ac, and causing this regression in the first place.
