### ISSUE TITLE
Instructions on how to use mate-hud

### ISSUE THREAD

**Issue by desgua** [ubuntu-mate/mate-hud#46]
mate-hud is now on Ubuntu repositories (and probably on Debian and others distros), so it can be easily installed by something like `apt install mate-hud`.  But how one can use it?  
For example I'm on i3wm, I open a terminal and run:   
   
GTK_MODULES="$GTK_MODULES:unity-gtk-module"   
export $GTK_MODULES
export UBUNTU_MENUPROXY=1

Then from terminal I open a program (for example openoffice) and (1) the old menus are still there, and (2) I still can't figure out how to trigger the HUD to search for a menu entry.

**Comment by flexiondotorg** [comment]
Closed via https://github.com/ubuntu-mate/mate-hud/commit/d6cd57e474a8daca20ebfc70a2b9e8a44e78f22d
