### ISSUE TITLE
With the new theme it downgrades the user experience a lot. How to change it? Does it still use Rofi?

### ISSUE THREAD

**Issue by tio-trom** [ubuntu-mate/mate-hud#52]
I really liked when it used Rofi was a lot more user friendly. A simple list. Now the menu is shown as buttons and most of the time the text is cut off.

This is how it looks now with libre office:

![2022-03-15_03-19](https://user-images.githubusercontent.com/38043315/158292915-1c5d0356-c7de-495a-a105-23f315a807c3.png)

And this is how it was looking with Rofi:

![2022-03-15_03-20](https://user-images.githubusercontent.com/38043315/158293028-88910a14-affb-43ed-8d87-73f10cfc8644.png)

A lot more user friendly. How is it possible to switch back? Thanks

**Comment by twa022** [comment]
I agree. Opened a pull request #53 that makes the rofi theme configurable in gsettings.

**Comment by tio-trom** [comment]
Perfect! Must needed. Also if you can add how the theme can be changed - some small instructions of how to do that.

**Comment by flexiondotorg** [comment]
As I mention in @twa022 pull request, I do agree that adding a `.rasi` file specific to Ubuntu MATE would be ace and I would welcome that addition.

Ubuntu MATE 22.04 is fast approaching final beta, but if you can supply a decent `.rasi` in the next couple of days, I'd really appreciate it 🙇 The `docu` theme was the only one of those shipped in Debian/Ubuntu that integrated the best.

Closing this issue and the pull request to make the theme configurable has been merged and released. Thank you for that 💖
